title: Cashel Financial
email: info@cashelfinancial.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Cashel Financial provides financial services for companies of all types and sizes.
baseurl: "/pages" # the subpath of your site, e.g. /blog
url: "http://www.cashelfinancial.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: cashel-theme
